name: Build with Gradle using Batect

on:
  push:
    paths-ignore:
      - '*.md'
      - 'images/**'
  pull_request:
    paths-ignore:
      - '*.md'
      - 'images/**'
  workflow_dispatch:

jobs:
  # Does your code need to check against several JVM versions?
  build:
    name: Builds and tests for Gradle
    runs-on: ubuntu-latest
    # First run in GitHub actions - verify this
    # Afterwards, change to a comment
    strategy:
      matrix:
        include:
          - java: 17
          - java: 21

    steps:
      - name: Clone repository
        uses: actions/checkout@master

      - name: Validate Batect wrapper scripts
        uses: batect/batect-wrapper-validation-action@v0.4.0

      - name: Restore Batect caches
        uses: actions/cache@master
        env:
          cache-name: batect-cache
        with:
          path: ~/.batect
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/batect.xml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Restore Gradle caches
        uses: actions/cache@master
        env:
          cache-name: gradle-cache
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{hashFiles('**/build.gradle') }}
          # TODO: See discussion: https://github.com/jeremylong/DependencyCheck/issues/2560#issuecomment-702098748
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Build and test
        run: ./batect build-with-gradle

      - name: Execute run script
        run: ./batect -o quiet run-with-gradle

      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jars
          path: build/libs/modern-java-practices*.jar
